Here were made small components in Components.js for ChooseCompetitio…
NadyaSakh/JudgeApp pull request #2
Opened 2018-06-15 12:42 UTC by NadyaSakh

…n screen.

2018-06-16 00:47 UTC, pewx2 requested changes
1. Исправить замечания
2. Переделать ActionContainer

2018-06-16 00:47 UTC, PewX2 commented on src/Screens/ChooseCompetition/Components.js
> +export const LoadingIndicator = (props) => {
- [ ] Если его и использовать, то нужен хотя бы стиль по-умолчанию
- [ ] Если один параметр, то скобки не ставим
- [ ] Он будет переиспользоваться? Тогда его место в общих компонентах

2018-06-16 00:47 UTC, PewX2 commented on src/Screens/ChooseCompetition/Components.js
> +export const SingleLineText = (props) => {
- [ ] Если один параметр, то скобки не ставим
- [ ] Добавь пропсы, чтобы это был по-настоящему текст в одну строку
- [ ]  Он будет переиспользоваться? Тогда его место в общих компонентах

2018-06-16 00:47 UTC, PewX2 commented on src/Screens/ChooseCompetition/Components.js
> +export const CompetitionItem = (props) => {
- [ ]  Если один параметр, то скобки не ставим

2018-06-16 00:47 UTC, PewX2 commented on src/Screens/ChooseCompetition/Components.js
> +export const CompetitionList = (props) => {
- [ ]  Если один параметр, то скобки не ставим

2018-06-16 00:47 UTC, PewX2 commented on src/Screens/ChooseCompetition/Components.js
> +    return (<FlatList
- [ ]  Убрать скобки

2018-06-16 00:47 UTC, PewX2 commented on src/Screens/ChooseCompetition/Components.js
> +                    onPress={() =>
- [ ] Исправить передачу функции в качестве параметра

Так делать плохо с т.з. производительности и памяти. Здесь на каждый элемент списка будет создаваться одна и та же функция. Сделай так:

1. Создать в компоненте функцию, которая будет вызывать переданную в качестве пропса функцию
`onPress = () => props.onPress()`

2. Теперь передаем эту функцию элементам списка (обрати внимание, что без скобок в конце, иначе функция будет вызывать при рендере элемента
`<CompetitionItem  onPress={this.onPress} />`

2018-06-16 00:47 UTC, PewX2 commented on src/Screens/ChooseCompetition/Components.js
> +export const Info = (props) => {
- [ ]  Убрать скобки

2018-06-16 00:47 UTC, PewX2 commented on src/Screens/ChooseCompetition/Components.js
> +export const screenError = (props) => {
- [ ]  Убрать скобки
- [ ] Компоненты называются с большой буквы

2018-06-16 00:47 UTC, PewX2 commented on src/Screens/ChooseCompetition/Components.js
> +    if (props.screenState === ScreenState.ERROR)
Неверное поведение. Этот компонент должен просто отображать что-то, а когда отображать должен решать родительский компонент

2018-06-16 08:29 UTC, NadyaSakh commented on src/Screens/ChooseCompetition/Components.js
> +    if (props.screenState === ScreenState.ERROR)
Просто тогда отображать алерт?

2018-06-16 08:37 UTC, NadyaSakh commented on src/Screens/ChooseCompetition/Components.js
> +                    onPress={() =>
То есть сделать в компоненте функцию, которая будет возвращать функцию из пропса, 
а потом её вызывать в <CompetitionItem onPress={this.onPress} />.  А остальное style, text можно оставить так: 
<CompetitionItem
onPress={this.onPress}
style={props.style}
text={item.key}/>  ?

Не совсем разницу поняла между этими вызовами функции. Всё запутано(

2018-06-20 23:30 UTC, NadyaSakh commented on src/Screens/ChooseCompetition/Components.js
> +export const LoadingIndicator = (props) => {
Стиль по умолчанию вроде есть

2018-06-20 23:32 UTC, NadyaSakh commented on src/Screens/ChooseCompetition/Components.js
> +export const SingleLineText = (props) => {
Не поняла про добавить пропсы, тут же они и передаются в функцию

2018-06-21 01:59 UTC, PewX2 commented on src/Screens/ChooseCompetition/Components.js
> +export const LoadingIndicator = (props) => {
По стилю: имел ввиду, что у компонента есть свой стиль по-умолчанию, который используется, если не передали стиль пропсом

2018-06-21 02:03 UTC, PewX2 commented on src/Screens/ChooseCompetition/Components.js
> +export const SingleLineText = (props) => {
Здесь передается только стиль, но если этот компонент всегда выводит текст в одну строку, то где соответствующий пропс у текста? 
https://facebook.github.io/react-native/docs/text.html#numberoflines

2018-06-21 03:22 UTC, pewx2 requested changes
Исправить замечания

2018-06-21 03:22 UTC, pewx2 commented on src/Screens/ChooseCompetition/Components.js
> +        props.onPress()
Это обычная функция, а не компонент. Данные на входе - это обычные объекты, а не пропсы. Пропсы только у компонентов

2018-06-21 03:22 UTC, pewx2 commented on src/Screens/ChooseCompetition/Components.js
>  export class ActionContainer extends React.PureComponent {
Этот компонент будет переиспользоваться в других экранах. Вынеси его в общие компоненты

2018-06-21 03:22 UTC, pewx2 commented on src/Screens/ChooseCompetition/Components.js
> +            <Info
Зачем при загрузке показывать этот компонент? По идее должно быть так:

```
<Info />
<ActionContainer/> //здесь, в зависимости от состояния показываешь загрузку, контент или ошибку
```

2018-06-21 03:22 UTC, pewx2 commented on src/Screens/ChooseCompetition/Components.js
> +        LoadingIndicator: PropTypes.object,
Посмотри еще раз пример, который я тебе скинул и разберись какие пропсы передаются в ActionContainer и где они потом используются.

2018-07-02 01:57 UTC, pewx2 approved these changes

2018-07-02 01:57 UTC, pewx2 commented on src/Screens/ChooseCompetition/Components.js
>          competitionList: PropTypes.array,
Переименовать в competitions

2018-07-02 01:57 UTC, merged